# Generated by Django 3.1.5 on 2021-01-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('content', models.TextField()),
                ('region', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('features', models.TextField()),
                ('image', models.ImageField(upload_to='pictures')),
            ],
        ),
    ]
